name: ClaimRewards
author: Mas281
version: ${project.version}

depend: [ActionUtil]
main: me.itsmas.claimrewards.ClaimRewards
api-version: 1.14

commands:
  claim:
    description: Claim a reward
  claimrewards:
    description: ClaimRewards main command
    aliases: [cr]